version: "3.3"

services:
  hub:
    image: selenium/hub
    networks:
    - private
    ports:
    - 4444:4444

  chrome:
    image: selenium/node-chrome
    networks:
    - private
    depends_on:
    - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
    volumes:
    - /dev/shm:/dev/shm # Mitigates the Chromium issue described at https://code.google.com/p/chromium/issues/detail?id=519952

  # firefox:
  #   image: selenium/node-firefox
  #   environment:
  #     HUB_PORT_4444_TCP_ADDR: hub
  #   links:
  #   - selenium-hub:hub

networks:
  private:
    driver: bridge